"""
Codex agent for autonomous vulnerability patching.

Implements the agent interface (setup / run) using Codex CLI
in agentic mode. Codex reads AGENTS.md for workflow instructions,
then autonomously: analyzes the crash → edits source → builds via libCRS
→ tests via libCRS → iterates → writes one final .diff to patches_dir.
"""

import logging
import os
import signal
import subprocess
import time
from pathlib import Path

logger = logging.getLogger("agent.codex")

_raw_model = os.environ.get("CODEX_MODEL", "gpt-5.2-codex").strip()
CODEX_MODEL = _raw_model.removeprefix("openai/").removeprefix("anthropic/")

# 0 = no timeout (run until budget is exhausted)
try:
    AGENT_TIMEOUT = int(os.environ.get("AGENT_TIMEOUT", "0"))
except ValueError:
    AGENT_TIMEOUT = 0
if AGENT_TIMEOUT < 0:
    AGENT_TIMEOUT = 0

_TEMPLATE_PATH = Path(__file__).with_suffix(".md")
_SECTIONS_DIR = _TEMPLATE_PATH.with_name("sections")

def _load_section(section_name: str) -> str:
    section_path = _SECTIONS_DIR / section_name
    return section_path.read_text()


def _load_prompt_templates() -> dict[str, str]:
    return {
        "agents_md": _TEMPLATE_PATH.read_text(),
        "workflow_pov": _load_section("workflow_pov.md"),
        "workflow_static": _load_section("workflow_static.md"),
        "pov_present": _load_section("pov_present.md"),
        "pov_absent": _load_section("pov_absent.md"),
        "bug_candidates_present": _load_section("bug_candidates_present.md"),
        "bug_candidates_absent": _load_section("bug_candidates_absent.md"),
        "pre_submit": _load_section("pre_submit.md"),
    }


def _toml_quote(value: str) -> str:
    """Return a TOML-safe quoted string for simple values."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _md_inline(value: str) -> str:
    """Return a markdown-safe inline code span."""
    ticks = 1
    while "`" * ticks in value:
        ticks += 1
    fence = "`" * ticks
    return f"{fence}{value}{fence}"


def _snapshot_patch_state(patches_dir: Path) -> dict[str, tuple[int, int]]:
    """Capture patch file state by name -> (mtime_ns, size)."""
    state: dict[str, tuple[int, int]] = {}
    for p in patches_dir.glob("*.diff"):
        try:
            st = p.stat()
        except OSError:
            continue
        state[p.name] = (st.st_mtime_ns, st.st_size)
    return state


def _changed_patches(
    before: dict[str, tuple[int, int]], patches_dir: Path
) -> list[str]:
    """Return sorted patch names that are new or modified since snapshot."""
    now = _snapshot_patch_state(patches_dir)
    return sorted(name for name, state in now.items() if before.get(name) != state)


def setup(source_dir: Path, config: dict) -> None:
    """One-time agent configuration.

    - Sets Codex-specific env vars/config (CODEX_HOME/config.toml, IS_SANDBOX)
    - Configures non-interactive no-approval mode for autonomous patching
    - Writes AGENTS.md into source_dir with libCRS tool docs + workflow
    """
    llm_api_url = config.get("llm_api_url", "")
    llm_api_key = config.get("llm_api_key", "")
    codex_home = Path(config.get("codex_home", Path.home() / ".codex"))
    codex_home.mkdir(parents=True, exist_ok=True)
    codex_log_dir = codex_home / "log"
    codex_log_dir.mkdir(parents=True, exist_ok=True)

    # CRS patcher container is intentionally permissive (autonomous mode).
    os.environ["IS_SANDBOX"] = "1"
    os.environ["CODEX_HOME"] = str(codex_home)

    config_lines = [
        "# Auto-generated by CRS Codex agent",
        f"model = {_toml_quote(CODEX_MODEL)}",
        "approval_policy = \"never\"",
        "sandbox_mode = \"danger-full-access\"",
        f"log_dir = {_toml_quote(str(codex_log_dir))}",
        "",
    ]

    if llm_api_url and llm_api_key:
        os.environ["OSS_CRS_LLM_API_KEY"] = llm_api_key
        config_lines.extend(
            [
                "model_provider = \"oss_crs\"",
                "",
                "[model_providers.oss_crs]",
                "name = \"OSS-CRS LiteLLM\"",
                f"base_url = {_toml_quote(llm_api_url)}",
                "env_key = \"OSS_CRS_LLM_API_KEY\"",
                "wire_api = \"responses\"",
                "",
            ]
        )
        logger.info("Codex configured with LiteLLM proxy: %s", llm_api_url)
    else:
        logger.warning(
            "No OSS_CRS_LLM_API_URL/KEY provided. Codex will use its default provider config."
        )

    codex_config = codex_home / "config.toml"
    codex_config.write_text("\n".join(config_lines))
    codex_config.chmod(0o600)
    logger.info("Wrote Codex config to %s", codex_config)
    logger.info("Model: %s", CODEX_MODEL)

    # Global gitignore so runtime instructions never leak into patches.
    global_gitignore = Path.home() / ".gitignore"
    existing = ""
    if global_gitignore.exists():
        existing = global_gitignore.read_text(errors="replace")
    lines = [line.rstrip("\n") for line in existing.splitlines()]
    if "AGENTS.md" not in lines:
        lines.append("AGENTS.md")
    global_gitignore.write_text("\n".join(lines).rstrip("\n") + "\n")
    try:
        git_cfg = subprocess.run(
            ["git", "config", "--global", "core.excludesFile", str(global_gitignore)],
            capture_output=True,
        )
        if git_cfg.returncode != 0:
            logger.warning(
                "Failed to set global git excludesFile: %s",
                git_cfg.stderr.decode(errors="replace") if isinstance(git_cfg.stderr, bytes) else git_cfg.stderr,
            )
    except OSError as e:
        logger.warning("Failed to run git config for excludesFile: %s", e)

    logger.info("Agent setup complete")


def run(
    source_dir: Path,
    povs: list[Path],
    bug_candidates: list[Path],
    diffs: list[Path],
    seeds: list[Path],
    harness: str,
    patches_dir: Path,
    work_dir: Path,
    *,
    language: str = "c",
    sanitizer: str = "address",
    builder: str,
) -> bool:
    """Launch Codex in agentic mode to autonomously fix the vulnerability.

    povs is a list of POV paths (possibly empty).
    bug_candidates is a list of static finding files (possibly empty).
    Writes available evidence and AGENTS.md (with concrete paths), then sends a prompt.
    Codex autonomously analyzes, edits, builds, tests, iterates, and
    writes the final .diff to patches_dir.

    Returns True if a patch file was produced in patches_dir.
    """
    work_dir.mkdir(parents=True, exist_ok=True)
    try:
        templates = _load_prompt_templates()
    except OSError as e:
        logger.error("Failed to load prompt template(s): %s", e)
        return False

    pov_sections = []
    for pov_path in povs:
        pov_sections.append(
            f"- POV: {_md_inline(str(pov_path))}\n"
            f"  Reproduce/Test: {_md_inline(f'libCRS run-pov {pov_path} <response_dir> --harness {harness} --build-id <build_id> --builder {builder}')}"
        )

    if pov_sections:
        pov_list = "\n".join(pov_sections)
        pov_section = templates["pov_present"].format(
            pov_count=len(povs),
            pov_list=pov_list,
        )
        workflow_section = templates["workflow_pov"]
        pre_submit_pov = "- [ ] `pov_exit_code` = 0 for EVERY provided POV variant\n"
    else:
        pov_section = templates["pov_absent"]
        workflow_section = templates["workflow_static"]
        pre_submit_pov = ""

    bug_candidate_list = "\n".join(f"- {_md_inline(str(p))}" for p in bug_candidates)
    if bug_candidate_list:
        bug_candidate_section = templates["bug_candidates_present"].format(
            bug_candidate_list=bug_candidate_list
        )
    else:
        bug_candidate_section = templates["bug_candidates_absent"]

    diff_list = "\n".join(f"- {_md_inline(str(p))}" for p in diffs)
    if diff_list:
        diff_section = (
            "## Diff Files\n\n"
            "Boot-time diff files were provided for this run:\n\n"
            f"{diff_list}\n\n"
            "Inspect any relevant diff files directly if they help localize the vulnerability.\n"
        )
    else:
        diff_section = ""

    seed_list = "\n".join(f"- {_md_inline(str(p))}" for p in seeds)
    if seed_list:
        seed_section = (
            "## Seed Files\n\n"
            "Boot-time seed files were provided for this run:\n\n"
            f"{seed_list}\n"
        )
    else:
        seed_section = ""

    if diffs:
        diff_validation_hint = (
            "- [ ] Patch considers the provided diff context when relevant\n"
        )
    else:
        diff_validation_hint = ""

    pre_submit_section = templates["pre_submit"].format(
        pov_line=pre_submit_pov,
        diff_line=diff_validation_hint,
    )

    # Write AGENTS.md with concrete paths for all available evidence.
    agents_md = templates["agents_md"].format(
        language=language,
        sanitizer=sanitizer,
        work_dir=work_dir,
        harness=harness,
        patches_dir=patches_dir,
        workflow_section=workflow_section,
        pov_section=pov_section,
        bug_candidate_section=bug_candidate_section,
        seed_section=seed_section,
        pre_submit_section=pre_submit_section,
        builder=builder,
        diff_section=diff_section,
    )
    (source_dir / "AGENTS.md").write_text(agents_md)

    target = os.environ.get("OSS_CRS_TARGET", source_dir.name)

    # Build dynamic top-level prompt based on available evidence.
    prompt_lines = [
        f"Fix the {sanitizer} vulnerability in project {_md_inline(target)} (harness: {_md_inline(harness)}).",
        "",
        "Available evidence:",
        f"- POV variants: {len(povs)}",
        f"- Bug-candidate files: {len(bug_candidates)}",
        f"- Diff files: {len(diffs)}",
        f"- Seed files: {len(seeds)}",
    ]
    if povs:
        pov_files = " ".join(_md_inline(str(p)) for p in povs)
        prompt_lines.append(f"- POV files: {pov_files}")
    if bug_candidates:
        bug_files = " ".join(_md_inline(str(p)) for p in bug_candidates)
        prompt_lines.append(f"- Bug-candidate report files: {bug_files}")
    if diffs:
        diff_files = " ".join(_md_inline(str(p)) for p in diffs)
        prompt_lines.append(f"- Diff files: {diff_files}")
    if seeds:
        seed_files = " ".join(_md_inline(str(p)) for p in seeds)
        prompt_lines.append(f"- Seed files: {seed_files}")
    prompt_lines.extend(
        [
            "",
            "Read AGENTS.md for workflow, tools, and submission instructions.",
        ]
    )
    prompt = "\n".join(prompt_lines)

    stdout_log = work_dir / "codex_stdout.log"
    stderr_log = work_dir / "codex_stderr.log"

    cmd = [
        "codex",
        "exec",
        "--cd",
        str(source_dir),
        "--skip-git-repo-check",
        "--dangerously-bypass-approvals-and-sandbox",
        "--model",
        CODEX_MODEL,
        "--json",
        prompt,
    ]

    # Stream stdout/stderr to files. Additional Codex debug logs are under $CODEX_HOME/log.

    existing_patches = _snapshot_patch_state(patches_dir)

    try:
        with open(stdout_log, "w") as out_f, open(stderr_log, "w") as err_f:
            proc = subprocess.Popen(
                cmd,
                stdout=out_f,
                stderr=err_f,
                text=True,
                cwd=source_dir,
                start_new_session=True,
            )
            try:
                proc.wait(timeout=AGENT_TIMEOUT or None)
                logger.info("Codex exit code: %d", proc.returncode)
            except subprocess.TimeoutExpired:
                logger.warning("Codex timed out (%ds), killing process tree", AGENT_TIMEOUT)
                try:
                    os.killpg(proc.pid, signal.SIGTERM)
                    time.sleep(2)
                    if proc.poll() is None:
                        os.killpg(proc.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                proc.wait()
                logger.info("Codex exit code after timeout handling: %d", proc.returncode)
    except Exception as e:
        logger.error("Error running Codex: %s", e)
        return False

    if proc.returncode != 0:
        logger.warning("Codex failed (rc=%d), see %s", proc.returncode, stderr_log)

    # Check if agent produced new patch files in this run.
    changed_patches = _changed_patches(existing_patches, patches_dir)
    if changed_patches:
        logger.info(
            "Agent produced %d updated/new patch(es): %s",
            len(changed_patches),
            changed_patches,
        )
        return True

    logger.info("Agent did not produce a patch")
    return False
